### ISSUE TITLE
Broken permalinks

### ISSUE THREAD

**Issue by axilleas** [schneems/schneems#1]
Hi there!

I'm reading your blog (thanks for the UT on rails!) and I noticed that the pager to go to a previous/next post isn't working. I guess this commit is to blame https://github.com/schneems/schneems/commit/bd8a2c311eaea57d2e3f17b737f6efa86868a3ff

Same happens when navigating the tags page, links are also broken.
Could this be resolved if you enabled `BASE_PATH` in `_config.yml`?

**Comment by schneems** [comment]
This should be fixed.
