### ISSUE TITLE
Several Tumblr posts are missing

### ISSUE THREAD

**Issue by wolfgang42** [schneems/schneems#17]
I was reading through your archives and stumbled across some posts that are listed in the index but just lead to a blank page:
```
$ find _posts/ -size 0 | sort
./_posts/tumblr/2012-01-30-hi-im-looking-for-the-correct-way-to-convert-a-gzip.html
./_posts/tumblr/2012-09-21-thank-you-so-much-for-the-article-raise-hell.html
./_posts/tumblr/2012-11-23-hi-there-i-wonder-what-do-you-think-about-mongodb-and.html
./_posts/tumblr/2013-05-05-dear-richard-i-stumbled-upon-your-videos-after.html
./_posts/tumblr/2013-05-05-hello-richard-i-was-curious-after-you-worked-at.html
./_posts/tumblr/2013-05-05-hey-man-i-just-wanted-to-say-thank-you-for-putting-the.html
./_posts/tumblr/2013-05-14-you-have-the-best-lesson-on-rails-hands-down-coming.html
./_posts/tumblr/2013-05-18-hi-richard-i-love-your-videos-thanks-so-much-times-a.html
./_posts/tumblr/2013-07-30-just-wanted-to-say-thanks-again-for-all-the-lessons.html
./_posts/tumblr/2013-08-26-hi-richard-thanks-for-the-tutorial-it-is-great-i-am.html
```

Other than this minor hiccup, I've been finding your posts to be very interesting reading. Thank you!

**Comment by schneems** [comment]
Most of those are actually other people saying "thanks" for content that I "reblogged" which is like a tumblr retweet.

Others are questions I answered. 

Funny enough that first post is one asking me about another blog post that went missing

https://schneems.tumblr.com/post/16765433402/hi-im-looking-for-the-correct-way-to-convert-a

You can see the actual "posts" here https://schneems.tumblr.com/. I would have to manually import each one by one if I wanted to keep them.
